on:
 pull_request:
 push:
   branches: [master]
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: cachix/install-nix-action@v14
        with:
          install_url: https://nixos-nix-install-tests.cachix.org/serve/vij683ly7sl95nnhb67bdjjfabclr85m/install
          install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v7
        with:
          name: arianvp
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - uses: actions/cache@v2
        id: nix-eval-cache
        with:
          path: $HOME/.cache/nix
          key: ${{ runner.os }}-${{ hashFiles('**/flake.nix') }}-${{ hashFiles('**/flake.lock') }}

      - name: Build app
        run: |
          git status
          nix build --print-build-logs --log-format raw .#
          nix build --print-build-logs --log-format raw --rebuild # Build again to check reproducibility
      - name: Build container
        run: nix build --print-build-logs  --log-format raw .#container

      - name: Push container
        run: |
          imageTag="$(nix eval --raw .#container.imageTag)"
          skopeo copy --dest-creds "$DOCKER_LOGIN" docker-archive:./result "docker://quay.io/arianvp/webauthn-oidc:$imageTag"

          skopeo copy --dest-creds "$DOCKER_LOGIN" "docker://quay.io/arianvp/webauthn-oidc:"{"$imageTag","${{ github.sha }}"}
        env:
          DOCKER_LOGIN: '${{ secrets.DOCKER_LOGIN }}'
