on:
 pull_request:
 push:
   branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v3'
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v10
        with:
          name: webauthn-oidc
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - uses: actions/cache@v2
        id: nix-eval-cache
        with:
          path: $HOME/.cache/nix
          key: ${{ runner.os }}-${{ hashFiles('**/flake.nix') }}-${{ hashFiles('**/flake.lock') }}
      - name: Build app
        run: |
          nix build -L 
      - name: Build container
        run: |
          nix build -L .#container

      - name: Push container
        run: |
          revParse=$(git rev-parse HEAD)
          imageTag="$(nix eval --raw .#container.imageTag)"
          skopeo copy --dest-creds "$DOCKER_LOGIN" docker-archive:./result "docker://quay.io/arianvp/webauthn-oidc:$imageTag"

          skopeo copy --dest-creds "$DOCKER_LOGIN" "docker://quay.io/arianvp/webauthn-oidc:"{"$imageTag","${{ github.sha }}"}
        env:
          DOCKER_LOGIN: '${{ secrets.DOCKER_LOGIN }}'
